### PR TITLE
Modernize Example plugin 

### PR DESCRIPTION
**Pull request by DinoChiesa**
Modernize Example plugin, use modern JS and defensive coding.

### CODE REVIEW

**Comment by DinoChiesa** [comment]
I am unsure why the CLA from henschkowski is still marked as missing.

**Comment by ssvaidyanathan** [comment]
henschkowski needs to submit CLA
The other PR has the same check failed

**Comment by DinoChiesa** [comment]
ok

**Comment by ssvaidyanathan** [comment]
Closing this as #284 has the fix for this

**Pull request closed without merging**
