### PR TITLE
feat: AssignMessage hygiene checks

### PR DESCRIPTION
**Pull request by DinoChiesa**
checks for presence of elements, proper placement, etc.

### CODE REVIEW

**Comment by DinoChiesa** [comment]
Wait, this is a work-in-progress.  Some adjustments coming.

**Comment by ssvaidyanathan** [comment]
is this done so that I can review?

**Comment by DinoChiesa** [comment]
Yes @ssvaidyanathan ready for review.

**Review by ssvaidyanathan — COMMENTED** [review]
LGTM

**Pull request merged**
