### PR TITLE
update policy name convention enforcement to allow patterns

### PR DESCRIPTION
**Pull request by DinoChiesa**
- eg, name of CORS policy can be "CORS", with no suffix. Similarly with Quota and HMAC policies.

- new tests for same.

- also added in metadata for JWT policy types.

### CODE REVIEW

**Comment by ssvaidyanathan** [comment]
@DinoChiesa - Can we also include GraphQL?

**Comment by DinoChiesa** [comment]
Yes - let me make that change.

**Comment by kurtkanaskie** [comment]
Graph QL could be GQ-parse or GQ-validate or GQ-parse-validate, those are the different uses.

**Comment by DinoChiesa** [comment]
For prefixes, I used only "graphql" , not GQ.   Do we want GQ? 
also the policy can be just "GraphQL", also.  IE, either `GraphQL-suffix` or `GraphQL`.

**Comment by kurtkanaskie** [comment]
I prefer to use 2 letter prefixes for all my policies.
I would like to have "GQ" as a valid prefix.

**Comment by DinoChiesa** [comment]
Kurt, I will add "GQ" as a prefix for the GraphQL policy.

**Pull request merged**
