### PR TITLE
Rationalize policy name attribute, and policy DisplayName

### PR DESCRIPTION
**Pull request by DinoChiesa**
This pull request provides changes that affect Policy.js class, and three dependent checks:  PO006, PO007, PO008.  

| item | before | after | 
| ---- | ---- | ----- |
| Policy.getDisplayName()  | returned the DisplayName, if it was present, and if not, the value of the name attribute. | returns the value of the DisplayName, or null if not present |
| PO006 | not implemented | checks that policy filename agrees with policy name attribute (Policy.getName())  | 
| PO007 | compares Policy.**getDisplayName()** against various patterns | compares Policy.**getName()** against various patterns |  
| PO008 | compares Policy.getDisplayName() against filename | unchanged implementation, but because Policy.js now returns ONLY the DisplayName, this check will appear to behave differently at runtime. | 

These changes will be backwards incompatible: Teams using apigeelint today that get no errors, may begin to see some errors when they adopt a version of apigeelint that contains these changes. Conversely, in some situations in which apigeelint prior to this change throws no errors today, an apigeelint with this change will begin to throw errors. Teams may need to adjust their apigeelint command lines  (exclude PO008, etc) or change their policies (make the name attribute consistent with the filename) to avoid these errors.

Submitted for your review and consideration.

### CODE REVIEW

**Comment by kurtkanaskie** [comment]
I don't think we should break backward compatibility on PO007 or PO008 as it doesn't provide any enhanced functionality. Furthermore, many developers incorporate apigeelint into their CI/CD pipelines, so this could have significant impact. 

The current behavior of policy.js getDisplayName() returning the attribute name aligns with the UI behavior of displaying the policy attribute name when DisplayName element is not present. That seems OK and I think it is the intension of PO007 to encourage consistent naming conventions when viewed in the UI. It's unfortunate that the "changling" issue exists, on uploads and downloads of proxy bundles, but I don't think that should be a reason to break backward compatibility, in fact we should be thankful that issue was identified by apigeelint, as that situation should be avoided.

I'm all for implementing PO006 without impacting PO007 or PO008. A note on the PO006 enhancement:

In checkPolicyNameAttribute.js line 19 where: name: "Check File and Display Naming"
should be: name: "Check File and Policy Attribute Name"

**Comment by karsten-wagner** [comment]
I buy into the change based on discussion in #154 

If the backwards compatibility is a strong driver, then eventually `Policy.getDisplayName()` might remain unchanged, since the current version seems to be in line with Apigee default behavior. This would also leave the behavior of PO008 unchanged, limiting the breaking change.

Implementing rule PO006 is a good idea in my view, since this matches also default behavior of Apigee. Even though it may lead to impact for existing users, I feel like they would be trapped in inconsistent setup today and so introducing a new rule that increases consistency would be in line with the general objective of apigeelint as a whole.

The change on PO007 feels consistent for me, since I always understood the naming prefix recommendations are aiming on the policy name attribute. However given the "allowed" prefixes, it was working well for my team so far to apply those rules also on the DisplayName. For those teams who do not maintain the DisplayName at all, the old setup of `Policy.getDisplayName()` would lead to the fallback behavior of still checking the name attribute against the recommended pattern.

Overall I think it is a good idea to provide rules that allow checking the file name to match against the name attribute and also DisplayName, so teams can chose which way they prefer. Activating both can even ask to have all three consistent, which would also be the case when DisplayName is not provided, but there is the fallback to use the name attribute then.

As said in #154 for my team we would end up in deactivating rule PO008, since we have the demand to sync the name attribute with the file name (new rule PO006) and have the DisplayName different...

My takeaway is that reverting the proposed change of `Policy.getDisplayName()` leads to significant less impact to existing users, while the other proposed changes greatly contribute to the apigeelint objectives...

**Comment by DinoChiesa** [comment]
Kurt, Karsten, good comments. 

Let's consider a different change that does not modify the (imo broken) Policy.getDisplayName().  

That method would still do the cascading thing, first retrieving the value of DisplayName and if there is none, falling back to the name attribute.

Therefore PO007 and PO008 would remain the same. 
PO006 would be new, and it would behave as I described above (just checking the name attribute).  Also, I'd need to introduce an additional new check (PO027 ?) that would behave like PO007 except it would work only on the name attribute, and not on the DisplayName. 

Karsten, with this imagined change, you'd have to use `-e PO008 -e PO007` to avoid any checks of DisplayName. 

Which illustrates an important point: This imagined change in which we preserve the exact current behavior of PO008 and PO007 _still_ introduces back-compat issues with apigeelint, because of the way apigeelint works. Specifically, if we add new plugins, those plugins will run. If I introduce two new checks (PO006 and PO027), those could potentially fail on existing proxies.  So, one way or the other, there will be back-compat issues. 

1. If we do the former (original) proposed change, which adds PO006 and modifies the behavior of PO007 and PO008, then some people will need to exclude PO008, and/or change their policy names/definitions. 
2. If we do this modified change, which adds PO006 and PO027, but  keeps PO007 and PO008 the same, then ... people still need to make changes in their exclude lists or policy name configuration.  

If we add _any_ new checks, there is no good (non-surprising) way to avoid back-compat issues. 

Given that, do we want to make the effort to preserve the (imo broken) behavior of Policy.getDisplayName() ?

If we implemented Karsten's idea of a config file containing the list of checks to run... that would protect us from back-compat issues _in the future_. People could store `PO008, PO025` etc in their  config file, and regardless how many new plugins we added, only those specified in the file would run. But that imagined change wouldn't help us here, because we haven't implemented it yet.  The default behavior is "run all plugins".

**Comment by karsten-wagner** [comment]
@DinoChiesa - just one thought...
You can code the new plugins like the extensions work. Provide some docs on how to copy and paste them into that custom extensions folder and people can decide to manually opt in?!

And of course you are right - in the current design every new plugin potentially creates backwards compatibility issues.

**Comment by kurtkanaskie** [comment]
Right @karsten-wagner 
I thought of that too, in fact I have an enhancement in the works (-X) that that excludes all built in rules. Then you could put the rules you want in the extensions folder.

You're right too @DinoChiesa regarding any new rules detecting new issues, unless of course you specify a fixed version in your project's package.json.

**Comment by DinoChiesa** [comment]
Manual Opt-in for new plugins would solve our immediate problem but would come with its own drawbacks:
- complexify the upgrade process
- some people, if they skip the opt-in part, might not get the shiny new plugins we think are cool

So I'm not sure how to best resolve this. 

I _feel_ that documenting the changes related to these via release notes, and maybe bumping the release to v0.6.x, would be the simplest solution to all of this.  In other words, we make changes that are backwards-incompatible, and we just decribe them, and describe what people need to do to deal with these changes (in short: apply -e thoughtfully).   

Is this not acceptable? 
@ssvaidyanathan maybe you have an opinion?

**Comment by kurtkanaskie** [comment]
Users can opt in by selecting the version they want to use.

I think it's OK to add new plugins that detect issues that previously didn't cause an error, I don't think this constitutes a backward breaking change as [new functionality is being introduced](https://semver.org/#spec-item-7).

Changing the behavior of existing plugins is OK under the same notion that users are in control of the version they use. I think this is a backward breaking change and [requires the major version to be incremented](https://semver.org/#spec-item-8).

Bumping the release is a good idea, not sure why we are even using 0.x.x instead of 1.x.x since 0.x.x implies "Anything MAY change at any time". According to [SemVer](https://semver.org/#semantic-versioning-specification-semver) we should be incrementing the version major number on backward incompatible changes (e.g. 1.x.x --> 2.x.x).

**Comment by kurtkanaskie** [comment]
LGTM, we should consider this breaking change and bump the version to 1.0.0

**Pull request merged**
