### PR TITLE
Issue239 - support for PropertySetRef in AssignMessage via --profile command line option.

### PR DESCRIPTION
**Pull request by kurtkanaskie**
Review my approach to specifying and accessing the profile value.

### CODE REVIEW

**Comment by ssvaidyanathan** [comment]
LGTM

**Comment by ssvaidyanathan** [comment]
@DinoChiesa - can you please review and provide your +1

**Comment by DinoChiesa** [comment]
How do I vote -1 ?

In lib/package/plugins/PO026-assignVariableUsage.js , I don't see any logic to reject PropertySetRef as invalid when profile == 'apigee'.   That is probably unlikely, but we should have logic  to check for it.  

Also, there ought to be a test for this case.  An AssignMessage/AsssignVariable, with PropertySetRef, and profile=='apigee', should return a specific error.

**Comment by kurtkanaskie** [comment]
npm test returns:
  PO026 - PropertySetRef with --profile 'apigeex' for PO026-apigeex-proxy
    ✓ should NOT generate errors for ProperSetRef (56ms)

  PO026 - PropertySetRef with --profile 'apigee' for PO026-apigeex-proxy
    ✓ should generate errors for ProperSetRef (45ms)
...

**Pull request merged**
